name: Go CI

on:
  push:
    branches: [ main ]

env:
  GO_VERSION: 1.22
  POSTGRES_DB: itbookworm_test
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpassword

jobs:
  test:
    runs-on: ubuntu-latest
    script:
      - cd ./../app/
      - make test 