name: CI Pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run unit tests
        working-directory: ./app  
        run: make test
  lint:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint
        working-directory: ./app  
        run: make lint

  sonarqube:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=AnnaPanchekhina_book
            -Dsonar.organization=annapanchekhina
            -Dsonar.projectName="Book Project"
            -Dsonar.sources=.
            -Dsonar.exclusions=**/*_test.go

  deploy:
#    needs: [sonarqube]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: app

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: app  
          file: app/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            docker pull ${{ env.DOCKER_IMAGE }}:latest && \
            docker stop book-api || true && \
            docker rm book-api || true && \
            docker run -d \
              --name book-api \
              --restart always \
              -p 4000:4000 \
              -e DB_DSN=${{ secrets.DB_DSN }} \
              ${{ env.DOCKER_IMAGE }}:latest
          "