name: CI Pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run unit tests
        working-directory: ./app  
        run: make test
  lint:
  needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint
        working-directory: ./app  
        run: make lint